In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2013-01-01 -0.284604 -0.933469  0.098997  0.193849
2013-01-02 -0.154906  0.939757 -1.827047 -0.005126
2013-01-03 -0.342975 -1.452343  2.983670 -0.685732
2013-01-04 -0.067725 -2.670401 -0.394594 -1.392980
2013-01-05 -0.445094  0.763297 -0.663794  0.298800
2013-01-06 -1.575347 -0.145149 -1.639516 -0.112989

In [7]:
df2 = pd.DataFrame(
    {
        "A":1.0,
        "B":pd.Timestamp('20130102'),
        "C":pd.Series(1, index=list(range(4)), dtype="float32"), 
        "D":np.array([3] * 4, dtype="int32"),
        "E":pd.Categorical(['test', 'train', 'test', 'train']), 
        "F":'foo'
    }
)
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [26]:
pd.Categorical(df2.iloc[:,4]).codes

array([0, 1, 0, 1], dtype=int8)

In [28]:
df.head()

A         B         C         D
2013-01-01 -0.284604 -0.933469  0.098997  0.193849
2013-01-02 -0.154906  0.939757 -1.827047 -0.005126
2013-01-03 -0.342975 -1.452343  2.983670 -0.685732
2013-01-04 -0.067725 -2.670401 -0.394594 -1.392980
2013-01-05 -0.445094  0.763297 -0.663794  0.298800

In [29]:
df.tail()

A         B         C         D
2013-01-02 -0.154906  0.939757 -1.827047 -0.005126
2013-01-03 -0.342975 -1.452343  2.983670 -0.685732
2013-01-04 -0.067725 -2.670401 -0.394594 -1.392980
2013-01-05 -0.445094  0.763297 -0.663794  0.298800
2013-01-06 -1.575347 -0.145149 -1.639516 -0.112989

In [31]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [32]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [33]:
df.to_numpy()

array([[-0.28460362, -0.93346855,  0.09899714,  0.19384901],
       [-0.15490577,  0.93975697, -1.82704678, -0.00512554],
       [-0.34297483, -1.45234312,  2.9836696 , -0.68573248],
       [-0.06772459, -2.67040081, -0.39459357, -1.39297952],
       [-0.44509442,  0.76329741, -0.66379396,  0.29879953],
       [-1.57534701, -0.14514875, -1.63951625, -0.1129893 ]])

In [34]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [36]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.478442 -0.583051 -0.240381 -0.284030
std    0.553823  1.382667  1.742861  0.642843
min   -1.575347 -2.670401 -1.827047 -1.392980
25%   -0.419565 -1.322624 -1.395586 -0.542547
50%   -0.313789 -0.539309 -0.529194 -0.059057
75%   -0.187330  0.536186 -0.024401  0.144105
max   -0.067725  0.939757  2.983670  0.298800

In [37]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.284604   -0.154906   -0.342975   -0.067725   -0.445094   -1.575347
B   -0.933469    0.939757   -1.452343   -2.670401    0.763297   -0.145149
C    0.098997   -1.827047    2.983670   -0.394594   -0.663794   -1.639516
D    0.193849   -0.005126   -0.685732   -1.392980    0.298800   -0.112989

In [38]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01  0.193849  0.098997 -0.933469 -0.284604
2013-01-02 -0.005126 -1.827047  0.939757 -0.154906
2013-01-03 -0.685732  2.983670 -1.452343 -0.342975
2013-01-04 -1.392980 -0.394594 -2.670401 -0.067725
2013-01-05  0.298800 -0.663794  0.763297 -0.445094
2013-01-06 -0.112989 -1.639516 -0.145149 -1.575347

In [41]:
df.sort_values(by="B")

A         B         C         D
2013-01-04 -0.067725 -2.670401 -0.394594 -1.392980
2013-01-03 -0.342975 -1.452343  2.983670 -0.685732
2013-01-01 -0.284604 -0.933469  0.098997  0.193849
2013-01-06 -1.575347 -0.145149 -1.639516 -0.112989
2013-01-05 -0.445094  0.763297 -0.663794  0.298800
2013-01-02 -0.154906  0.939757 -1.827047 -0.005126

In [42]:
df['A']

2013-01-01   -0.284604
2013-01-02   -0.154906
2013-01-03   -0.342975
2013-01-04   -0.067725
2013-01-05   -0.445094
2013-01-06   -1.575347
Freq: D, Name: A, dtype: float64

In [43]:
df[0:3]

A         B         C         D
2013-01-01 -0.284604 -0.933469  0.098997  0.193849
2013-01-02 -0.154906  0.939757 -1.827047 -0.005126
2013-01-03 -0.342975 -1.452343  2.983670 -0.685732

In [44]:
df['20130101':'20130104']

A         B         C         D
2013-01-01 -0.284604 -0.933469  0.098997  0.193849
2013-01-02 -0.154906  0.939757 -1.827047 -0.005126
2013-01-03 -0.342975 -1.452343  2.983670 -0.685732
2013-01-04 -0.067725 -2.670401 -0.394594 -1.392980

In [49]:
df.iloc[0,:]

A   -0.284604
B   -0.933469
C    0.098997
D    0.193849
Name: 2013-01-01 00:00:00, dtype: float64

In [50]:
df.loc[:,["A","B"]]

A         B
2013-01-01 -0.284604 -0.933469
2013-01-02 -0.154906  0.939757
2013-01-03 -0.342975 -1.452343
2013-01-04 -0.067725 -2.670401
2013-01-05 -0.445094  0.763297
2013-01-06 -1.575347 -0.145149

In [53]:
df.loc["20130102":"20130104", ["A", "B"]]

A         B
2013-01-02 -0.154906  0.939757
2013-01-03 -0.342975 -1.452343
2013-01-04 -0.067725 -2.670401

In [54]:
df.loc[dates[0], 'A']

-0.2846036237878227

In [57]:
df.iloc[3]

A   -0.067725
B   -2.670401
C   -0.394594
D   -1.392980
Name: 2013-01-04 00:00:00, dtype: float64

In [58]:
df.iloc[3:5, 0:2]

A         B
2013-01-04 -0.067725 -2.670401
2013-01-05 -0.445094  0.763297

In [59]:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2013-01-02 -0.154906 -1.827047
2013-01-03 -0.342975  2.983670
2013-01-05 -0.445094 -0.663794

In [60]:
df.iloc[1:3, :]

A         B         C         D
2013-01-02 -0.154906  0.939757 -1.827047 -0.005126
2013-01-03 -0.342975 -1.452343  2.983670 -0.685732

In [61]:
df.iloc[:, 1:3]

B         C
2013-01-01 -0.933469  0.098997
2013-01-02  0.939757 -1.827047
2013-01-03 -1.452343  2.983670
2013-01-04 -2.670401 -0.394594
2013-01-05  0.763297 -0.663794
2013-01-06 -0.145149 -1.639516

In [62]:
df.iloc[1, 1]

0.9397569705340396

In [67]:
df[df["B"] > 0]

A         B         C         D
2013-01-02 -0.154906  0.939757 -1.827047 -0.005126
2013-01-05 -0.445094  0.763297 -0.663794  0.298800

In [68]:
df[df > 0]

A         B         C         D
2013-01-01 NaN       NaN  0.098997  0.193849
2013-01-02 NaN  0.939757       NaN       NaN
2013-01-03 NaN       NaN  2.983670       NaN
2013-01-04 NaN       NaN       NaN       NaN
2013-01-05 NaN  0.763297       NaN  0.298800
2013-01-06 NaN       NaN       NaN       NaN

In [69]:
df2 = df.copy()
df2["E"] = ["one", "one", "two", "three", "four", "three"]
df2

A         B         C         D      E
2013-01-01 -0.284604 -0.933469  0.098997  0.193849    one
2013-01-02 -0.154906  0.939757 -1.827047 -0.005126    one
2013-01-03 -0.342975 -1.452343  2.983670 -0.685732    two
2013-01-04 -0.067725 -2.670401 -0.394594 -1.392980  three
2013-01-05 -0.445094  0.763297 -0.663794  0.298800   four
2013-01-06 -1.575347 -0.145149 -1.639516 -0.112989  three

In [70]:
df2[df2["E"].isin(["two", "four"])]

A         B         C         D     E
2013-01-03 -0.342975 -1.452343  2.983670 -0.685732   two
2013-01-05 -0.445094  0.763297 -0.663794  0.298800  four

In [71]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))

In [72]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [73]:
df ["F"] = s1
df

A         B         C         D    F
2013-01-01 -0.284604 -0.933469  0.098997  0.193849  NaN
2013-01-02 -0.154906  0.939757 -1.827047 -0.005126  1.0
2013-01-03 -0.342975 -1.452343  2.983670 -0.685732  2.0
2013-01-04 -0.067725 -2.670401 -0.394594 -1.392980  3.0
2013-01-05 -0.445094  0.763297 -0.663794  0.298800  4.0
2013-01-06 -1.575347 -0.145149 -1.639516 -0.112989  5.0